/**
 * Curated icon set for the team icon picker (~100 icons).
 * Keys must be valid Lucide icon names — verified against lucide-react exports.
 */
import {
  Users,
  Shield,
  Swords,
  Trophy,
  Flag,
  Zap,
  Crown,
  Target,
  Flame,
  Rocket,
  Ghost,
  Skull,
  Heart,
  Star,
  Gem,
  Anchor,
  Compass,
  Globe,
  Castle,
  Footprints,
  Leaf,
  Music,
  Camera,
  Gamepad2,
  Puzzle,
  Mountain,
  Waves,
  Trees,
  Banana,
  Beer,
  Pizza,
  Coffee,
  Dumbbell,
  Bike,
  Sailboat,
  Plane,
  Car,
  Train,
  Bus,
  Ship,
  Tent,
  Telescope,
  Microscope,
  Atom,
  Dna,
  FlaskConical,
  Magnet,
  Battery,
  Radio,
  Cpu,
  Monitor,
  Keyboard,
  Mouse,
  Printer,
  Server,
  Database,
  Cloud,
  Lock,
  Key,
  Eye,
  Search,
  Bell,
  Book,
  BookOpen,
  Bookmark,
  Tag,
  Ticket,
  Gift,
  ShoppingCart,
  Briefcase,
  Calculator,
  Calendar,
  Clock,
  Map,
  MapPin,
  Navigation,
  Sun,
  Moon,
  CloudLightning,
  Wind,
  Snowflake,
  Droplets,
  Diamond,
  Hexagon,
  Triangle,
  Circle,
  Square,
  Shuffle,
  Layers,
  BarChart2,
  PieChart,
  TrendingUp,
  Activity,
  Aperture,
  Crosshair,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export interface IconEntry {
  key: string
  icon: LucideIcon
}

export const TEAM_ICONS: IconEntry[] = [
  { key: 'Users', icon: Users },
  { key: 'Shield', icon: Shield },
  { key: 'Swords', icon: Swords },
  { key: 'Trophy', icon: Trophy },
  { key: 'Flag', icon: Flag },
  { key: 'Zap', icon: Zap },
  { key: 'Crown', icon: Crown },
  { key: 'Target', icon: Target },
  { key: 'Flame', icon: Flame },
  { key: 'Rocket', icon: Rocket },
  { key: 'Ghost', icon: Ghost },
  { key: 'Skull', icon: Skull },
  { key: 'Heart', icon: Heart },
  { key: 'Star', icon: Star },
  { key: 'Gem', icon: Gem },
  { key: 'Anchor', icon: Anchor },
  { key: 'Compass', icon: Compass },
  { key: 'Globe', icon: Globe },
  { key: 'Castle', icon: Castle },
  { key: 'Footprints', icon: Footprints },
  { key: 'Leaf', icon: Leaf },
  { key: 'Music', icon: Music },
  { key: 'Camera', icon: Camera },
  { key: 'Gamepad2', icon: Gamepad2 },
  { key: 'Puzzle', icon: Puzzle },
  { key: 'Mountain', icon: Mountain },
  { key: 'Waves', icon: Waves },
  { key: 'Trees', icon: Trees },
  { key: 'Banana', icon: Banana },
  { key: 'Beer', icon: Beer },
  { key: 'Pizza', icon: Pizza },
  { key: 'Coffee', icon: Coffee },
  { key: 'Dumbbell', icon: Dumbbell },
  { key: 'Bike', icon: Bike },
  { key: 'Sailboat', icon: Sailboat },
  { key: 'Plane', icon: Plane },
  { key: 'Car', icon: Car },
  { key: 'Train', icon: Train },
  { key: 'Bus', icon: Bus },
  { key: 'Ship', icon: Ship },
  { key: 'Tent', icon: Tent },
  { key: 'Telescope', icon: Telescope },
  { key: 'Microscope', icon: Microscope },
  { key: 'Atom', icon: Atom },
  { key: 'Dna', icon: Dna },
  { key: 'FlaskConical', icon: FlaskConical },
  { key: 'Magnet', icon: Magnet },
  { key: 'Battery', icon: Battery },
  { key: 'Radio', icon: Radio },
  { key: 'Cpu', icon: Cpu },
  { key: 'Monitor', icon: Monitor },
  { key: 'Keyboard', icon: Keyboard },
  { key: 'Mouse', icon: Mouse },
  { key: 'Printer', icon: Printer },
  { key: 'Server', icon: Server },
  { key: 'Database', icon: Database },
  { key: 'Cloud', icon: Cloud },
  { key: 'Lock', icon: Lock },
  { key: 'Key', icon: Key },
  { key: 'Eye', icon: Eye },
  { key: 'Search', icon: Search },
  { key: 'Bell', icon: Bell },
  { key: 'Book', icon: Book },
  { key: 'BookOpen', icon: BookOpen },
  { key: 'Bookmark', icon: Bookmark },
  { key: 'Tag', icon: Tag },
  { key: 'Ticket', icon: Ticket },
  { key: 'Gift', icon: Gift },
  { key: 'ShoppingCart', icon: ShoppingCart },
  { key: 'Briefcase', icon: Briefcase },
  { key: 'Calculator', icon: Calculator },
  { key: 'Calendar', icon: Calendar },
  { key: 'Clock', icon: Clock },
  { key: 'Map', icon: Map },
  { key: 'MapPin', icon: MapPin },
  { key: 'Navigation', icon: Navigation },
  { key: 'Sun', icon: Sun },
  { key: 'Moon', icon: Moon },
  { key: 'CloudLightning', icon: CloudLightning },
  { key: 'Wind', icon: Wind },
  { key: 'Snowflake', icon: Snowflake },
  { key: 'Droplets', icon: Droplets },
  { key: 'Diamond', icon: Diamond },
  { key: 'Hexagon', icon: Hexagon },
  { key: 'Triangle', icon: Triangle },
  { key: 'Circle', icon: Circle },
  { key: 'Square', icon: Square },
  { key: 'Shuffle', icon: Shuffle },
  { key: 'Layers', icon: Layers },
  { key: 'BarChart2', icon: BarChart2 },
  { key: 'PieChart', icon: PieChart },
  { key: 'TrendingUp', icon: TrendingUp },
  { key: 'Activity', icon: Activity },
  { key: 'Aperture', icon: Aperture },
  { key: 'Crosshair', icon: Crosshair },
]

/** Resolve an icon key string to the LucideIcon component, falling back to Shield. */
export function resolveIcon(key: string): LucideIcon {
  return TEAM_ICONS.find(e => e.key === key)?.icon ?? Shield
}
